### PR TITLE
molstar update

### PR DESCRIPTION
**Pull request by bioinsilico**
I updated molstar and rcsb-molstar and didn't observe any issues.  Do you have more details about how the app was failing?

### CODE REVIEW

**Comment by sbittrich** [comment]
Here are some test cases that were broken: https://rcsbpdb.atlassian.net/jira/software/c/projects/RO/issues/RO-4166

**Comment by bioinsilico** [comment]
Thank you, @JonStargaryen. Are the cases from the [example](https://www.rcsb.org/alignment?request-body=eJyVj0FrwzAMhf%2BLzhk0LSubbzkshx62susoRthyaojtTFbYQsh%2Fn73CYJfBbuJ9T3pPK7zPxAuoFdIkPsVcRyaZOepMBUZD2qIgKIdjpq0Bk6LQp1RjSJZAwYSeP3wmaCCQXJOtLGKozKEYlDv2g7eFT8hFF%2BJbUMhWm1mSc6AODaCbtPVZfrT2uNs14BiHQFH0SHGQK6iHrfTIwrMpRamceluhcF50CVHQvp5PJSvTSKY%2BVaMwL%2BFGOyjbv%2Fz7l6fn%2F%2Fi7Xnf9%2BfC4P9737d%2BLl9rU%2BfG75GX7AvYgfb8%3D&response-body=eJztV9tu2zgQ%2FRc%2F2wZv4qVvREUpXFGqbmBhFIHhJkpqIHFaX7obFPn3HTptI7uNnSZb7EuRB0fknOFoODPn6Mtgvri4Gbz6Mths5ueDV4P3RHaESzw6R6Ibse4Cj9SMzEYUXzCB3wvWsYvBcLBaz9abFdi%2FfpOXzrRmcDccXHfrWXA1u5pfLq67xXp6fXPegdHH2Xz593zVAbC3160%2F3IQjL2brs9l6tJxfQgTgZtmtNldrcP7uC5yz3JytN7C0fQTc8na6DRTX5V8hkO6qO1vPbxbbg1e31%2Fe7enB3N9yxJ29Mcdj%2BdPhw3PR7nNtzl90lQEIM73ZRw8H77nK66j5tF%2FD943xx3v0zeIWGg6tucbn%2BMHjFUIjmcSCjO0hGHqBEHYYKtgMVtAelh6EYRTtYjFgPHB0B092YMe0FjdGRowmVO2jCcC9bR7B72SKM98IWR8Bi952JkL2wGRTBwRuWj90wpONIvsKl9vPFVA995JIx3wPzHjgiR14Z891XJr0a4fjuFAp%2FvZwtVhc3y%2BvZ%2Bluh4yH6%2BvfT%2FyBRaEw4lVgqFkmOhMScDdFYEhwJzKhgGEdYseEIjSMUUYWkiJgCU6qCi3HEFWwTLARjNKLge0wUYohySZkQnJLgTnBFkBIRoUxhClcdoEJIQSTkXDAJHlQ4gykUKcEFQuBNUh7WqMIIK4GFkooqHgF4JNkY0QhAVG0jJEMcjRl4IVTQiDPJBR7yMYsookxiCCki8BY4pGm1ub6eLW%2FD7Fid3XybSp9nVxsYc2TMBGTy9mMYeXXexINwL183I8rHCH%2FfXs2v51ez5Xx9O9o6GoTps4Cps5iC1%2Fn5ppuGoQn%2BCY%2FuR1P3adMtzh6fTM8aTJjJY2WrXlK28gVlS9CBslUhJ5ezj%2FdvvhNgv6HDETsBHNgkpDeDSD%2FnITptJtp7l7WuKcrkrY%2FzLEutiY2GpdQ3PraJbsrGpHFSNZWrXGJisM2KCdjpRJeuaXzhfF56Xeu3AT1xsBCbzMZ5XLgs02laeKMT37Zx4bVPdZbqJrE2zlyqTZoar601KRgWukmNrusi1S0gANtUNnMefkodv41rm2kXe90W3lV1URbwbCevdRG3uc5TryvtdaHTrE0z77xP2zi1JXjMcoggrfJWt2BUgDMLR6Quc7mPtckasLelizNdmgQOjBvrfFtta%2F1pxfjoDD3KkvL5LClewJLoBSxJokMseYysKHk%2BS1L%2BApbk9AhL%2FrT3GOo30G53Cfz4nuqFJvdblvRmBt1vWaoe90pYdKDZ%2ByUQ7TV7nTrdZFnbtj711paxbQqbTLRxug49b3WbT7JJYS00eBNXRRVnxp04VxS5S7PKQy%2FZJG%2Bgm1tjTrwx0NxN6UsYIFo31jRtUdmy8a2NJ6bSOom1rxpn4yY9yQqYFr5JW2dMaYsTnWU%2BSydZrV1rmtSVvo6bifUwaCbtBBDWaG8yB%2BYwSspW2yR0s8k1jCV7kuoqhvcpfFnEzlibJnHR1q5pc1%2BXlWsb76syn4Qu9zqvnWuzSV5kpoXObqyvXHlSW5PUVdNmW5Y6yIFoDGT8neS%2BZnQ0Pwe6Aq77JUIc9pyGWt53%2BoDYtRUPAbT5j87IGMh8l6UPUG%2FYCR8xV935t93wvkTKISjJ%2B6rZQqGUwhQi4QtnMT27%2BdwtZ5dwxDtYUvx0%2BzXy333M6GSqk5IqiDDB%2F9tXDWThmF4m7CD4ucoTpB3inBPCGchO0H0Mbh2NFYdpQUGKYhUJ0HFBAhIOqg4hkIFSMipREJCwrBQiIB1FxAmY0q2CRArUHwGJCstMCrbFw%2FjHDEkEspVSRICDtngM8iRSFDPGYdJiKoJ6jWQwjATMbU7EVg2D3g0SOTxKgkhQvqAtJQLtCdEyCgFHsCIlIJQEkYuCxpWAoxKEL6OUU4TUE%2BQnKO%2F9wn6oeghiHPTTr8tPuKbfJz%2FvK%2BiPzvotOutI7%2B2kHSb%2BxGWTJNCOT10O%2FNBALv%2FcxrHbeEJXRs%2FvygdT%2FHQCVPggAf7E0wM%2FHxgDB6iQYvwDFQbAHhUGJa0ocOHp3b%2FTTDWV&encoded=true)?  I don't see any problems loading the structures.

**Comment by sbittrich** [comment]
> Are the cases from the [example](https://www.rcsb.org/alignment?request-body=eJyVj0FrwzAMhf%2BLzhk0LSubbzkshx62susoRthyaojtTFbYQsh%2Fn73CYJfBbuJ9T3pPK7zPxAuoFdIkPsVcRyaZOepMBUZD2qIgKIdjpq0Bk6LQp1RjSJZAwYSeP3wmaCCQXJOtLGKozKEYlDv2g7eFT8hFF%2BJbUMhWm1mSc6AODaCbtPVZfrT2uNs14BiHQFH0SHGQK6iHrfTIwrMpRamceluhcF50CVHQvp5PJSvTSKY%2BVaMwL%2BFGOyjbv%2Fz7l6fn%2F%2Fi7Xnf9%2BfC4P9737d%2BLl9rU%2BfG75GX7AvYgfb8%3D&response-body=eJztV9tu2zgQ%2FRc%2F2wZv4qVvREUpXFGqbmBhFIHhJkpqIHFaX7obFPn3HTptI7uNnSZb7EuRB0fknOFoODPn6Mtgvri4Gbz6Mths5ueDV4P3RHaESzw6R6Ibse4Cj9SMzEYUXzCB3wvWsYvBcLBaz9abFdi%2FfpOXzrRmcDccXHfrWXA1u5pfLq67xXp6fXPegdHH2Xz593zVAbC3160%2F3IQjL2brs9l6tJxfQgTgZtmtNldrcP7uC5yz3JytN7C0fQTc8na6DRTX5V8hkO6qO1vPbxbbg1e31%2Fe7enB3N9yxJ29Mcdj%2BdPhw3PR7nNtzl90lQEIM73ZRw8H77nK66j5tF%2FD943xx3v0zeIWGg6tucbn%2BMHjFUIjmcSCjO0hGHqBEHYYKtgMVtAelh6EYRTtYjFgPHB0B092YMe0FjdGRowmVO2jCcC9bR7B72SKM98IWR8Bi952JkL2wGRTBwRuWj90wpONIvsKl9vPFVA995JIx3wPzHjgiR14Z891XJr0a4fjuFAp%2FvZwtVhc3y%2BvZ%2Bluh4yH6%2BvfT%2FyBRaEw4lVgqFkmOhMScDdFYEhwJzKhgGEdYseEIjSMUUYWkiJgCU6qCi3HEFWwTLARjNKLge0wUYohySZkQnJLgTnBFkBIRoUxhClcdoEJIQSTkXDAJHlQ4gykUKcEFQuBNUh7WqMIIK4GFkooqHgF4JNkY0QhAVG0jJEMcjRl4IVTQiDPJBR7yMYsookxiCCki8BY4pGm1ub6eLW%2FD7Fid3XybSp9nVxsYc2TMBGTy9mMYeXXexINwL183I8rHCH%2FfXs2v51ez5Xx9O9o6GoTps4Cps5iC1%2Fn5ppuGoQn%2BCY%2FuR1P3adMtzh6fTM8aTJjJY2WrXlK28gVlS9CBslUhJ5ezj%2FdvvhNgv6HDETsBHNgkpDeDSD%2FnITptJtp7l7WuKcrkrY%2FzLEutiY2GpdQ3PraJbsrGpHFSNZWrXGJisM2KCdjpRJeuaXzhfF56Xeu3AT1xsBCbzMZ5XLgs02laeKMT37Zx4bVPdZbqJrE2zlyqTZoar601KRgWukmNrusi1S0gANtUNnMefkodv41rm2kXe90W3lV1URbwbCevdRG3uc5TryvtdaHTrE0z77xP2zi1JXjMcoggrfJWt2BUgDMLR6Quc7mPtckasLelizNdmgQOjBvrfFtta%2F1pxfjoDD3KkvL5LClewJLoBSxJokMseYysKHk%2BS1L%2BApbk9AhL%2FrT3GOo30G53Cfz4nuqFJvdblvRmBt1vWaoe90pYdKDZ%2ByUQ7TV7nTrdZFnbtj711paxbQqbTLRxug49b3WbT7JJYS00eBNXRRVnxp04VxS5S7PKQy%2FZJG%2Bgm1tjTrwx0NxN6UsYIFo31jRtUdmy8a2NJ6bSOom1rxpn4yY9yQqYFr5JW2dMaYsTnWU%2BSydZrV1rmtSVvo6bifUwaCbtBBDWaG8yB%2BYwSspW2yR0s8k1jCV7kuoqhvcpfFnEzlibJnHR1q5pc1%2BXlWsb76syn4Qu9zqvnWuzSV5kpoXObqyvXHlSW5PUVdNmW5Y6yIFoDGT8neS%2BZnQ0Pwe6Aq77JUIc9pyGWt53%2BoDYtRUPAbT5j87IGMh8l6UPUG%2FYCR8xV935t93wvkTKISjJ%2B6rZQqGUwhQi4QtnMT27%2BdwtZ5dwxDtYUvx0%2BzXy333M6GSqk5IqiDDB%2F9tXDWThmF4m7CD4ucoTpB3inBPCGchO0H0Mbh2NFYdpQUGKYhUJ0HFBAhIOqg4hkIFSMipREJCwrBQiIB1FxAmY0q2CRArUHwGJCstMCrbFw%2FjHDEkEspVSRICDtngM8iRSFDPGYdJiKoJ6jWQwjATMbU7EVg2D3g0SOTxKgkhQvqAtJQLtCdEyCgFHsCIlIJQEkYuCxpWAoxKEL6OUU4TUE%2BQnKO%2F9wn6oeghiHPTTr8tPuKbfJz%2FvK%2BiPzvotOutI7%2B2kHSb%2BxGWTJNCOT10O%2FNBALv%2FcxrHbeEJXRs%2FvygdT%2FHQCVPggAf7E0wM%2FHxgDB6iQYvwDFQbAHhUGJa0ocOHp3b%2FTTDWV&encoded=true)? I don't see any problems loading the structures.

Yes, that example was also broken (I think the AlphaFold structure loaded successfully but nothing was shown for the other 2 entries).

Great to have that fixed, thanks!

**Comment by valasatava** [comment]
Thank you, @bioinsilico. The versions that introduced a breaking changes were:
```
"@rcsb/rcsb-molstar": "^2.8.0"
"@rcsb/rcsb-saguaro-3d": "^3.0.18"
"molstar": "^3.40.1" -> "^3.37.1"
``` 
either there was an intermediate breaking mol* change or saguaro-3d update would introduce something

**Comment by bioinsilico** [comment]
I am unsure if it has been fixed or never broken. I just cannot reproduce the problem.

**Pull request closed without merging**
